import random_word_gen as rwg

#MAKE SURE YOU HAVE THE WORD GEN INSTALLED IN THE SAME FOLDER AS THIS

#countries end in лaнyдaя

#shorter list
arr1 = [
    'i',
    'you (singular)',
    'this',
    'who',
    'what',
    'one',
    'two',
    'fish',
    'dog',
    'louse',
    'blood',
    'bone',
    'egg',
    'horn',
    'tail',
    'ear',
    'eye',
    'nose',
    'tooth',
    'tongue',
    'hand',
    'know',
    'die',
    'give',
    'sun',
    'moon',
    'water',
    'salt',
    'stone',
    'wind',
    'fire',
    'year',
    'full',
    'new',
    'name',
]

#Swadesh 207 list
arr2 = [
    "i",
    "you (singular)",
    "he",
    "we",
    "you (plural)",
    "they",
    "this",
    "that",
    "here",
    "there",
    "who",
    "what",
    "where",
    'when',
    'how',
    'not',
    'all',
    'many',
    'some',
    'few',
    'other',
    'one',
    'two',
    'three',
    'four',
    'five',
    'big',
    'long',
    'wide',
    'thick',
    'heavy',
    'small',
    'short',
    'narrow',
    'thin',
    'woman',
    'man (adult male)',
    'man (human being)',
    'child',
    'wife',
    'husband',
    'mother',
    'father',
    'animal',
    'fish',
    'bird',
    'dog',
    'louse',
    'snake',
    'worm',
    'tree',
    'forest',
    'stick',
    'fruit',
    'seed',
    'leaf',
    'root',
    'bark (of a tree)',
    'flower',
    'grass',
    'rope',
    'skin'
    'meat',
    'blood',
    'bone',
    'fat (noun)',
    'egg',
    'horn',
    'tail',
    'feather',
    'hair',
    'head',
    'ear',
    'eye',
    'nose',
    'mouth',
    'tooth',
    'tongue (organ)',
    'fingernail',
    'foot',
    'leg',
    'knee',
    'hand',
    'wing',
    'belly',
    'guts',
    'neck',
    'back',
    'breast',
    'heart',
    'liver',
    'to drink',
    'to eat',
    "to bite",
    'to suck',
    'to spit',
    'to vomit',
    'to blow',
    'to breathe',
    'to laugh',
    'to see',
    'to hear',
    'to know',
    'to think',
    'to smell',
    'to fear',
    'to sleep',
    'to live',
    'to die',
    'to kill',
    'to fight',
    'to hunt',
    'to hit',
    'to cut',
    'to split',
    'to stab',
    'to scratch',
    'to dig',
    'to swim',
    'to fly',
    'to walk',
    'to come',
    'to lie (as in a bed)',
    'to sit',
    'to stand',
    'to turn (intransitive)',
    'to fall',
    'to give',
    'to hold',
    'to squeeze',
    'to rub',
    'to wash',
    'to wipe',
    'to pull',
    'to push',
    'to throw',
    'to tie',
    'to sew',
    'to count',
    'to say',
    'to sing',
    'to play',
    'to float',
    'to flow',
    'to freeze',
    'to swell',
    'sun',
    'moon',
    'star',
    'water',
    'rain',
    'river',
    'lake',
    'sea',
    'salt',
    'stone',
    'sand',
    'dust',
    'earth',
    'cloud',
    'fog',
    'sky',
    'wind',
    'snow',
    'ice',
    'smoke',
    'fire',
    'ash',
    'to burn',
    'road',
    'mountain',
    'red',
    'green',
    'yellow',
    'white',
    'black',
    'night',
    'day',
    'year',
    'warm',
    'cold',
    'full',
    'new',
    'old',
    'good',
    'bad',
    'rotten',
    'dirty',
    'straight',
    'round',
    'sharp (as a knife)',
    'dull (as a knife)',
    'smooth',
    'wet',
    'dry',
    'correct',
    'near',
    'far',
    'right',
    'left',
    'at',
    'in',
    'with',
    'and',
    'if',
    'because',
    'name',
]

#chidimo on github
countries = [
  'AFGHANISTAN',
  'ALBANIA',
  'ALGERIA',
  'AMERICAN SAMOA',
  'ANDORRA',
  'ANGOLA',
  'ANGUILLA',
  'ANTARCTICA',
  'ANTIGUA AND BARBUDA',
  'ARGENTINA',
  'ARMENIA',
  'ARUBA',
  'AUSTRALIA',
  'AUSTRIA',
  'AZERBAIJAN',
  'BAHAMAS',
  'BAHRAIN',
  'BANGLADESH',
  'BARBADOS',
  'BELARUS',
  'BELGIUM',
  'BELIZE',
  'BENIN',
  'BERMUDA',
  'BHUTAN',
  'BOLIVIA',
  'BOSNIA AND HERZEGOVINA',
  'BOTSWANA',
  'BOUVET ISLAND',
  'BRAZIL',
  'BRITISH INDIAN OCEAN TERRITORY',
  'BRUNEI DARUSSALAM',
  'BULGARIA',
  'BURKINA FASO',
  'BURUNDI',
  'CAMBODIA',
  'CAMEROON',
  'CANADA',
  'CAPE VERDE',
  'CAYMAN ISLANDS',
  'CENTRAL AFRICAN REPUBLIC',
  'CHAD',
  'CHILE',
  'CHINA',
  'CHRISTMAS ISLAND',
  'COCOS (KEELING) ISLANDS',
  'COLOMBIA',
  'COMOROS',
  'CONGO',
  'CONGO, THE DEMOCRATIC REPUBLIC OF',
  'COOK ISLANDS',
  'COSTA RICA',
  "CÃ”TE D'IVOIRE",
  'CROATIA',
  'CUBA',
  'CYPRUS',
  'CZECH REPUBLIC',
  'DENMARK',
  'DJIBOUTI',
  'DOMINICA',
  'DOMINICAN REPUBLIC',
  'ECUADOR',
  'EGYPT',
  'EL SALVADOR',
  'EQUATORIAL GUINEA',
  'ERITREA',
  'ESTONIA',
  'ETHIOPIA',
  'FALKLAND ISLANDS (MALVINAS)',
  'FAROE ISLANDS',
  'FIJI',
  'FINLAND',
  'FRANCE',
  'FRENCH GUIANA',
  'FRENCH POLYNESIA',
  'FRENCH SOUTHERN TERRITORIES',
  'GABON',
  'GAMBIA',
  'GEORGIA',
  'GERMANY',
  'GHANA',
  'GIBRALTAR',
  'GREECE',
  'GREENLAND',
  'GRENADA',
  'GUADELOUPE',
  'GUAM',
  'GUATEMALA',
  'GUINEA',
  'GUYANA',
  'HAITI',
  'HEARD ISLAND AND MCDONALD ISLANDS',
  'HONDURAS',
  'HONG KONG',
  'HUNGARY',
  'ICELAND',
  'INDIA',
  'INDONESIA',
  'IRAN, ISLAMIC REPUBLIC OF',
  'IRAQ',
  'IRELAND',
  'ISRAEL',
  'ITALY',
  'JAMAICA',
  'JAPAN',
  'JORDAN',
  'KAZAKHSTAN',
  'KENYA',
  'KIRIBATI',
  "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
  'KOREA, REPUBLIC OF',
  'KUWAIT',
  'KYRGYZSTAN',
  "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  'LATVIA',
  'LEBANON',
  'LESOTHO',
  'LIBERIA',
  'LIBYAN ARAB JAMAHIRIYA',
  'LIECHTENSTEIN',
  'LITHUANIA',
  'LUXEMBOURG',
  'MACAO',
  'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
  'MADAGASCAR',
  'MALAWI',
  'MALAYSIA',
  'MALDIVES',
  'MALI',
  'MALTA',
  'MARSHALL ISLANDS',
  'MARTINIQUE',
  'MAURITANIA',
  'MAURITIUS',
  'MAYOTTE',
  'MEXICO',
  'MICRONESIA, FEDERATED STATES OF',
  'MOLDOVA, REPUBLIC OF',
  'MONACO',
  'MONGOLIA',
  'MONTSERRAT',
  'MOROCCO',
  'MOZAMBIQUE',
  'MYANMAR',
  'NAMIBIA',
  'NAURU',
  'NEPAL',
  'NETHERLANDS',
  'NETHERLANDS ANTILLES',
  'NEW CALEDONIA',
  'NEW ZEALAND',
  'NICARAGUA',
  'NIGER',
  'NIGERIA',
  'NIUE',
  'NORFOLK ISLAND',
  'NORTHERN MARIANA ISLANDS',
  'NORWAY',
  'OMAN',
  'PAKISTAN',
  'PALAU',
  'PALESTINIAN TERRITORY, OCCUPIED',
  'PANAMA',
  'PAPUA NEW GUINEA',
  'PARAGUAY',
  'PERU',
  'PHILIPPINES',
  'PITCAIRN',
  'POLAND',
  'PORTUGAL',
  'PUERTO RICO',
  'QATAR',
  'RÃ‰UNION',
  'ROMANIA',
  'RUSSIAN FEDERATION',
  'RWANDA',
  'SAINT HELENA',
  'SAINT KITTS AND NEVIS',
  'SAINT LUCIA',
  'SAINT PIERRE AND MIQUELON',
  'SAINT VINCENT AND THE GRENADINES',
  'SAMOA',
  'SAN MARINO',
  'SAO TOME AND PRINCIPE',
  'SAUDI ARABIA',
  'SENEGAL',
  'SERBIA AND MONTENEGRO',
  'SEYCHELLES',
  'SIERRA LEONE',
  'SINGAPORE',
  'SLOVAKIA',
  'SLOVENIA',
  'SOLOMON ISLANDS',
  'SOMALIA',
  'SOUTH AFRICA',
  'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS',
  'SPAIN',
  'SRI LANKA',
  'SUDAN',
  'SURINAME',
  'SVALBARD AND JAN MAYEN',
  'SWAZILAND',
  'SWEDEN',
  'SWITZERLAND',
  'SYRIAN ARAB REPUBLIC',
  'TAIWAN, PROVINCE OF CHINA',
  'TAJIKISTAN',
  'TANZANIA, UNITED REPUBLIC OF',
  'THAILAND',
  'TIMOR',
  'TOGO',
  'TOKELAU',
  'TONGA',
  'TRINIDAD AND TOBAGO',
  'TUNISIA',
  'TURKEY',
  'TURKMENISTAN',
  'TURKS AND CAICOS ISLANDS',
  'TUVALU',
  'UGANDA',
  'UKRAINE',
  'UNITED ARAB EMIRATES',
  'UNITED KINGDOM',
  'UNITED STATES',
  'UNITED STATES MINOR OUTLYING ISLANDS',
  'URUGUAY',
  'UZBEKISTAN',
  'VANUATU',
  'VIET NAM',
  'VIRGIN ISLANDS, BRITISH',
  'VIRGIN ISLANDS, U.S.',
  'WALLIS AND FUTUNA',
  'WESTERN SAHARA',
  'YEMEN',
  'ZIMBABWE',
]

wl = []

arr = arr1

for i in range(len(arr2)):
    arr.append(arr2[i])

arr = list(dict.fromkeys(arr))

arr.sort()


for i in range(len(arr)):
    word = ""
    while word in wl:
        word = rwg.gen_word(rwg.set_length(3, 10))
    wl.append(word)
    print(arr[i] + " - " + word)


print()


arr = countries

for i in range(len(arr)):
    word = ""
    while word in wl:
        word = rwg.gen_word(rwg.set_length(3, 10))
    
    word = word.replace(word[0], word[0].upper())
    
    wl.append(word)
    print(arr[i] + " - " + word + "лaнyдaя")
